
import PoweredPrompt from "@/app/components/theme-pages/prompts/PoweredPrompt";
import BreadcrumbComp from "../../layout/shared/breadcrumb/BreadcrumbComp";
import type { Metadata } from "next";
import ContextAIaware from "@/app/components/theme-pages/prompts/ContextAiAware";
import PromptLibrary from "@/app/components/theme-pages/prompts/PromptLibrary";
import { Card } from "@/components/ui/card";

export const metadata: Metadata = {
    title: "Prompts Page",
    description: "Generated by create next app",
};
const BCrumb = [
    {
        to: "/",
        title: "Home",
    },
    {
        title: "Prompts",
    },
];

const Prompts = () => {
    return (
        <>
            <BreadcrumbComp title="Prompts" items={BCrumb} />
            <Card>
                <PoweredPrompt />
                <PromptLibrary />
                <ContextAIaware />
            </Card>
        </>
    );
};

export default Prompts;
